export const GET_TICKETS = 'GET_TICKETS';
export const GET_TICKETS_SUCCEEDED = 'GET_TICKETS_SUCCEEDED';
export const GET_TICKETS_FAILED = 'GET_TICKETS_FAILED';

export const GET_TICKET_DETAILS = 'GET_TICKET_DETAILS';
export const GET_TICKET_DETAILS_SUCCEEDED = 'GET_TICKET_DETAILS_SUCCEEDED';
export const GET_TICKET_DETAILS_FAILED = 'GET_TICKET_DETAILS_FAILED';

export const CREATE_TICKET = 'CREATE_TICKET';
export const CREATE_TICKET_SUCCEEDED = 'CREATE_TICKET_SUCCEEDED';
export const CREATE_TICKET_FAILED = 'CREATE_TICKET_FAILED';
export const CLEAR_CREATE_TICKET_DATA = 'CLEAR_CREATE_TICKET_DATA';

export const UPDATE_TICKET = 'UPDATE_TICKET';
export const UPDATE_TICKET_SUCCEEDED = 'UPDATE_TICKET_SUCCEEDED';
export const UPDATE_TICKET_FAILED = 'UPDATE_TICKET_FAILED';

export const REPLY_TO_TICKET = 'REPLY_TO_TICKET';
export const REPLY_TO_TICKET_SUCCEEDED = 'REPLY_TO_TICKET_SUCCEEDED';
export const REPLY_TO_TICKET_FAILED = 'REPLY_TO_TICKET_FAILED';

